In [1]:
import numpy as np 
arr = np.array([10,20,30,40])
print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())


100
25.0
10
40


In [3]:
arr = np.array([10,20,30,40])
print(arr*5)

[ 50 100 150 200]


In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [11]:
print(arr)
print(arr[0])
print(arr[3])

for i in range(1,4):
    print(arr[i],",")


print(arr*2)
print(arr.shape)


[10 20 30 40]
10
40
20 ,
30 ,
40 ,
[20 40 60 80]
(4,)


In [ ]:
import numpy as np 
arr1 = np.array([
                [10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr)
print(arr.shape)
print("printing specific:",arr1[1,1])

print("first row:")
for i in range(0,3):
    print(arr1[i,0])

print("first column:")
for i in range(0,3):
    print(arr1[0,i])

print("printing last row :")
for i in range(0,3):
    print(arr1[2,i])

print("printing the sum array :",arr1.sum())

print("printing maximum value",arr1.max())

print("multplying every element by 3 : ",arr1*3)
print("Adding 5 everyi element : ",arr1+5)






[10 20 30 40]
(4,)
printing specific: 50
first row:
10
40
70
first column:
10
20
30
printing last row :
70
80
90
printing the sum array : 450
printing maximum value 90
multplying every element by 3 :  [[ 30  60  90]
 [120 150 180]
 [210 240 270]]
Adding 5 everyi element :  [[15 25 35]
 [45 55 65]
 [75 85 95]]
40
None


In [42]:
print(arr1[0:2,1:3])


[[20 30]
 [50 60]]
