In [ ]:
import numpy as np 
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

print( "matrix shape :",matrix.shape)

print(matrix[0])
print(matrix[0][1])
print(matrix[1][2])



[[1 2 3]
 [4 5 6]]
matrix shape : (2, 3)
[1 2 3]
2
6


In [5]:

#slicing concept
arr = np.array([10,20,30,40,50])
print(arr[1:4])
print(arr[:3])
print(arr[2:])


[20 30 40]
[10 20 30]
[30 40 50]


In [9]:
#task 1:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr1)
print("shaping: ",arr1.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shaping:  (3, 3)


In [ ]:
#task 2:
print(arr1[1,1])



5


In [19]:
# task 3 : 1d array make of 10 number ans print middle five numbers using slicing 
arr2 = np.array([1,2,3,4,5,6,7,8,9,])
print("slicinng :",arr2[3:8])

slicinng : [4 5 6 7 8]


In [27]:
#task 4 : make 2d array 3x3 and print first row ,and second column 

print(arr1[0])
print(arr1[:,1])

[1 2 3]
[2 5 8]
