In [30]:
#revision 
def average(a,b):
    return (a+b)/2

a = int(input("enter the number :"))
b = int(input("enter the number :"))

print("the average of two number is ",average(a,b))

the average of two number is  72.5


In [31]:
furit = ["apple ","banana","pappay","stawberrey","pineapple"]
for index,furit in enumerate(furit):
    print(f"index : {index},furit name: {furit}")


index : 0,furit name: apple 
index : 1,furit name: banana
index : 2,furit name: pappay
index : 3,furit name: stawberrey
index : 4,furit name: pineapple


In [32]:
profile = {
    "name":"abhijeet",
    "age":20,
    "eduction":"undergraudute",
    "DOB":"28/12/2005"

}

print(f"i'm {profile['name']} my age is {profile['age']} and educiton is currtently {profile['eduction']} date of birth is {profile['DOB']} ")

i'm abhijeet my age is 20 and educiton is currtently undergraudute date of birth is 28/12/2005 


In [33]:
def calculator(a,b,op):
    try:
        if op == "+":
             print(a+b)
        elif op == "-":
                print(a-b)
        elif op == "*":
                print(a*b)
        elif op == "/":
                 print(a/b)
        else:
              print("invalid opertion")


    except ValueError:
          print("you entered worng number")
    except ZeroDivisionError:
          print("can't divide by zero ")

a = int(input("enter number :"))
b = int(input("enter number :"))
op = input("opertion (+,-,*,/):")

calculator(a,b,op)



invalid opertion


In [34]:
#oop
class person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def greet(self):
        print(f"i'm {self.name} and age {self.age}")

# p1 = person("abhijeet",20)
# p1.greet()
        
class student(person):
    def __init__(self, name, age,college):
        super().__init__(name, age)
        self.college = college
    def greet(self):
        print(f"i'm {self.name} and age {self.age} i studying in {self.college}")

s1 = student("abhi",20,"JIT")
s1.greet()


i'm abhi and age 20 i studying in JIT


In [35]:
# part numpy A
import numpy as np
arr = np.array([1,2,3,4,5,6,7,9])

print("Array",arr)
print("maximum ",arr.max())
print("sum",arr.sum())
print("mimum",arr.min())


Array [1 2 3 4 5 6 7 9]
maximum  9
sum 37
mimum 1


In [36]:
import numpy as np 
matrix = np.array([[1,2,3,],
                 [4,5,6],
                 [7,8,9]])
print("columns:")
print(matrix[:,0])
print(matrix[:,1])
print(matrix[:,2])
print("rows:")
print(matrix[0,:])
print(matrix[1,:])
print(matrix[2,:])

columns:
[1 4 7]
[2 5 8]
[3 6 9]
rows:
[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
# part 4 pandas
import pandas as pd
data = {
    "name":["aaditi","abhijeet","abhinav","abhishek","anchal"],
    "age":[20,21,20,19,20],
    "mark":[90,99,43,54,67],
    "city":["nagpur","bhandara","nagpur","bhandara","nagpur"]

}

df = pd.DataFrame(data)
print(df)


result = df[df["mark"]>60]

# print(result)

print("-----------------------")
sorted_mark = result.sort_values("mark")
print(sorted_mark)

print("___________________")
average_marks = df.groupby("name")["mark"].mean()
print(average_marks)

       name  age  mark      city
0    aaditi   20    90    nagpur
1  abhijeet   21    99  bhandara
2   abhinav   20    43    nagpur
3  abhishek   19    54  bhandara
4    anchal   20    67    nagpur
-----------------------
       name  age  mark      city
4    anchal   20    67    nagpur
0    aaditi   20    90    nagpur
1  abhijeet   21    99  bhandara
___________________
name
aaditi      90.0
abhijeet    99.0
abhinav     43.0
abhishek    54.0
anchal      67.0
Name: mark, dtype: float64


In [38]:
# adding new column in table result pass aur fail
df["result"]=df["mark"].apply(lambda x: "pass" if x >= 60 else "fail")
print(df)

       name  age  mark      city result
0    aaditi   20    90    nagpur   pass
1  abhijeet   21    99  bhandara   pass
2   abhinav   20    43    nagpur   fail
3  abhishek   19    54  bhandara   fail
4    anchal   20    67    nagpur   pass


In [42]:
# task a
print("task A")
result1 = df[(df["age"]>20) & (df["mark"]>70)]
print(result)

# task b 
print("task B")
city_max = df.groupby("city")["mark"].max()
print(city_max)

# task c 
print("Task c")
df["grade"] = df["mark"].apply(lambda x: "A" if x>=90 else ("B" if x >=60 else "c") )
# instead of that lamda method we also can do creating seperate fuction for grade and the we put function .apply(funtion) 
print(df)

task A
       name  age  mark      city
0    aaditi   20    90    nagpur
1  abhijeet   21    99  bhandara
4    anchal   20    67    nagpur
task B
city
bhandara    99
nagpur      90
Name: mark, dtype: int64
Task c
       name  age  mark      city result grade
0    aaditi   20    90    nagpur   pass     A
1  abhijeet   21    99  bhandara   pass     A
2   abhinav   20    43    nagpur   fail     c
3  abhishek   19    54  bhandara   fail     c
4    anchal   20    67    nagpur   pass     B
